### PR TITLE
added some tools

### PR DESCRIPTION
**Pull request by PatrickAlphaC**
Hello!

I added a few tools like Optik, Halmos, and Solidity's built-in checker.

I also added a note about the term "invariant testing". Technically, invariant testing is just "stateful fuzzing" but foundry calls it "invariant testing". Regular fuzzing is also technically invariant testing, but foundry counts invariants specifically as stateful fuzz tests. 

There has been some discussion on this topic asking for a better name in foundry: https://github.com/foundry-rs/foundry/issues/4162

Nice work on this, looking forward to future information.

You could also look into Trail of Bits' [Maat](https://maat.re/), Microsoft's [z3](https://microsoft.github.io/z3guide/docs/logic/intro/), or the [Certora](https://www.certora.com/) online IDE for formal verification.

### CODE REVIEW

**Comment by ZhangZhuoSJTU** [comment]
Hello @PatrickAlphaC,

Thank you for the update. Your help in expanding the tools list is much appreciated, and as someone who is not an expert in verification, I always welcome the opportunity to learn more.

Regarding Maat and Z3, my understanding is that they are general SymEx / Solver and may not be the most appropriate tools to include in the list. I am currently exploring [Certora](https://www.certora.com/) and would be grateful for any further suggestions you may have.

Once again, thank you for your contributions to this project.

**Comment by PatrickAlphaC** [comment]
For sure. Maat & Z3 are more generic SymEx, which is a kind of [formal verification](https://ethereum.stackexchange.com/questions/145361/whats-the-difference-between-smt-solvers-and-formal-verification). Maat, in particular, is used in Echidna as a [hybrid fuzzer](https://blog.trailofbits.com/2022/12/08/hybrid-echidna-fuzzing-optik-maat/), to make fuzzing more intelligent. 

Curious, why the closed PR instead of just removing Maat & Z3?

**Comment by ZhangZhuoSJTU** [comment]
> Curious, why the closed PR instead of just removing Maat & Z3?

Please accept my apologies as I may not fully comprehend your question.

The pull request you submitted has been successfully merged into the main branch and subsequently closed. If there is anything further that I can do to assist you with this matter, please don't hesitate to let me know.

**Comment by PatrickAlphaC** [comment]
I clearly need to go to sleep. For some reason, I thought the PR was just closed, and I didn't understand why because your comment sounded happy to get the PR!

I was being dumb, sorry! And thanks for this research study!

**Pull request merged**
